name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8, 11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          cache: "maven"
          distribution: "temurin"
      - name: Build, test, coverage
        run: ./mvnw clean test jacoco:report
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty: true
          base-path: src/main/java
          parallel: true
          flag-name: run-jvm-${{ join(matrix.*, '-') }}
  finish:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: run-jvm-8,run-jvm-11,run-jvm-17

