on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8,11,17]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          cache: 'maven'
          distribution: 'temurin'
      - name: Build, test, coverage
        run: ./mvnw clean test jacoco:report coveralls:report
